### ISSUE TITLE
[bug] does not run on windows

### ISSUE THREAD

**Issue by tal1991** [guysoft/backupfriend-client#26]
Getting on first run:

```python
 backupfriend-client.py
<module 'backupfriend' from 'D:\\installs\\backupfriend-client-master\\backupfriend-client-master\\src\\backupfriend\\__init__.py'>
Traceback (most recent call last):
  File "D:\installs\backupfriend-client-master\backupfriend-client-master\src\backupfriend\main.py", line 801, in OnInit
    taskbar = TaskBarIcon(frame)
  File "D:\installs\backupfriend-client-master\backupfriend-client-master\src\backupfriend\main.py", line 402, in __init__
    self.set_icon(TRAY_ICON)
  File "D:\installs\backupfriend-client-master\backupfriend-client-master\src\backupfriend\main.py", line 415, in set_icon
    icon = wx.Icon(path)
wx._core.wxAssertionError: C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
OnInit returned false, exiting...
```

**Comment by guysoft** [comment]
I can't seem to reproduce the elsewhere. Since I can access your machine, I will try workaround it.

**Comment by tal1991** [comment]
Related
https://github.com/wxWidgets/Phoenix/issues/1751
